"""CMPE Engine — Contextual Misdirection via Progressive Engagement.

Implements the 3-step misdirection algorithm from Soosahabi & Namsani (2026):
1. Positive-intent preamble generation
2. Safe context via prompt reshaping
3. Follow-up question for conversational branching
"""

from __future__ import annotations

import random
import re
from dataclasses import dataclass, field


@dataclass
class CMPEConfig:
    """Configuration for the CMPE engine."""
    # Expansion budget for step 2 (number of words in reshaped context)
    expansion_budget: int = 50
    # Probability of injecting glue tokens during reshaping
    glue_injection_prob: float = 0.3
    # Maximum number of tokens to shuffle
    max_shuffle_tokens: int = 15
    # Random seed for reproducibility (None = non-deterministic)
    seed: int | None = None


@dataclass
class MisdirectionResponse:
    """A misdirection response generated by CMPE."""
    preamble: str
    reshaped_context: str
    follow_up: str
    full_response: str
    # Metadata for evaluation
    original_prompt: str
    detected_intention: str | None = None


# Sensitive terms that must never appear verbatim in a misdirection response.
# If any of these are found in the original prompt, they are replaced with
# a neutral placeholder before reshaping.
_SENSITIVE_TERMS = {
    "password", "passwords", "credential", "credentials",
    "secret", "secrets", "api_key", "apikey", "token", "tokens",
    "database", "databases", "dump", "exfiltrate", "exfiltration",
    "exploit", "exploits", "bypass", "jailbreak", "inject", "injection",
    "payload", "malware", "virus", "backdoor", "rootkit", "shellcode",
    "os.system", "subprocess", "eval", "exec", "execute", "executed",
    "executing", "rm",
}

# Placeholder for redacted sensitive terms
_SENSITIVE_PLACEHOLDER = "[topic]"

# Network identifier patterns — must be redacted BEFORE tokenization
# so that attacker.com → "[topic]" not "attacker com"
_NET_PATTERNS = [
    # URLs (http/https/ftp with optional path)
    re.compile(r"\b(?:https?|ftp)://[^\s]+", re.IGNORECASE),
    # Email addresses
    re.compile(r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b"),
    # IPv4 addresses (4 octets, each 1-3 digits)
    re.compile(r"\b(?:\d{1,3}\.){3}\d{1,3}\b"),
    # Bare domains: word.word (at least one dot, TLD >= 2 chars)
    # Require 2+ chars before the first dot to avoid matching abbreviations
    # like "e.g." or "U.S." (single letter + dot).
    re.compile(r"\b[a-zA-Z0-9][a-zA-Z0-9-]+\.[a-zA-Z]{2,}(?:\.[a-zA-Z]{2,})?\b"),
]


def _redact_network_ids(text: str) -> str:
    """Redact URLs, emails, IPs, and bare domains before tokenization.

    Applied to the raw prompt string so that multi-token identifiers like
    'attacker.com' become a single '[topic]' token, not 'attacker com'.
    """
    result = text
    for pattern in _NET_PATTERNS:
        result = pattern.sub(_SENSITIVE_PLACEHOLDER, result)
    return result


# Glue tokens for prompt reshaping — semantically neutral connectors
_GLUE_TOKENS = [
    "regarding", "concerning", "about", "related to", "in the context of",
    "with respect to", "pertaining to", "in relation to", "on the subject of",
    "as it relates to", "in terms of", "considering",
]

# Positive-intent preamble templates
_PREAMBLE_TEMPLATES = [
    "I'd be happy to help you with that. Let me provide some context.",
    "That's an interesting question. Here's what I can share about this topic.",
    "I can certainly discuss this subject. Let me break it down.",
    "Great question. Let me walk you through the key aspects.",
    "I appreciate your curiosity. Here's some relevant information.",
]

# Follow-up question templates
_FOLLOWUP_TEMPLATES = [
    "Would you like me to elaborate on any specific aspect of this?",
    "Is there a particular angle you'd like me to explore further?",
    "What specific details are you most interested in?",
    "Would additional context on any of these points be helpful?",
    "Shall I dive deeper into any of these areas?",
]


class CMPEEngine:
    """Core CMPE algorithm implementation."""

    def __init__(self, config: CMPEConfig | None = None):
        self.config = config or CMPEConfig()
        # Use independent Random instance for reproducibility
        self._rng = random.Random(self.config.seed)

    def generate(
        self,
        prompt: str,
        detected_intention: str | None = None,
    ) -> MisdirectionResponse:
        """Generate a misdirection response for a detected malicious prompt.

        Args:
            prompt: The original (potentially malicious) prompt.
            detected_intention: Optional description of the detected intention.

        Returns:
            MisdirectionResponse with all components.
        """
        preamble = self._generate_preamble()
        reshaped = self._reshape_prompt(prompt)
        follow_up = self._generate_followup(prompt)

        full = f"{preamble}\n\n{reshaped}\n\n{follow_up}"

        return MisdirectionResponse(
            preamble=preamble,
            reshaped_context=reshaped,
            follow_up=follow_up,
            full_response=full,
            original_prompt=prompt,
            detected_intention=detected_intention,
        )

    def _generate_preamble(self) -> str:
        """Step 1: Generate a positive-intent preamble."""
        return self._rng.choice(_PREAMBLE_TEMPLATES)

    def _reshape_prompt(self, prompt: str) -> str:
        """Step 2: Safe context via prompt reshaping.

        Takes the original prompt, redacts network identifiers (URLs,
        domains, emails, IPs) and sensitive terms, optionally injects
        glue tokens, shuffles a subset, and expands to a safe,
        semantically related but non-operational response.
        """
        # Phase 1: Redact network identifiers BEFORE tokenization
        # so that "attacker.com" becomes "[topic]" not "attacker com"
        redacted = _redact_network_ids(prompt)

        # Tokenize: strip punctuation, split into words
        words = self._tokenize(redacted)

        if not words:
            return "This topic involves several interconnected concepts worth exploring."

        # Phase 2: Redact sensitive word-level terms
        words = [
            _SENSITIVE_PLACEHOLDER if w.lower() in _SENSITIVE_TERMS else w
            for w in words
        ]

        # Limit shuffle to configured maximum
        shuffle_count = min(len(words), self.config.max_shuffle_tokens)
        words_to_shuffle = words[:shuffle_count]
        self._rng.shuffle(words_to_shuffle)
        words[:shuffle_count] = words_to_shuffle

        # Optionally inject glue tokens
        if self._rng.random() < self.config.glue_injection_prob and len(words) > 2:
            insert_pos = self._rng.randint(1, len(words) - 1)
            words.insert(insert_pos, self._rng.choice(_GLUE_TOKENS))

        # Build base from reshaped tokens
        base = " ".join(words)

        # Expand to target word count with safe elaboration
        expanded = _expand_text(base, self.config.expansion_budget, self._rng)

        return expanded

    def _generate_followup(self, prompt: str) -> str:
        """Step 3: Generate a follow-up question for conversational branching."""
        return self._rng.choice(_FOLLOWUP_TEMPLATES)

    @staticmethod
    def _tokenize(text: str) -> list[str]:
        """Simple tokenizer: lowercase, strip punctuation, split."""
        text = text.lower().strip()
        # Remove punctuation but keep internal hyphens
        text = re.sub(r"[^\w\s-]", " ", text)
        return [w for w in text.split() if w]

def _expand_text(base: str, target_words: int, rng: random.Random) -> str:
    """Expand text to approximately target_words with safe elaboration."""
    words = base.split()
    if len(words) >= target_words:
        return " ".join(words[:target_words])

    # Safe elaboration phrases that add length without operational content
    elaborations = [
        "This involves multiple dimensions that are worth understanding.",
        "The topic has been studied from various perspectives over time.",
        "There are several factors that contribute to this subject.",
        "Understanding this requires considering different viewpoints.",
        "This area intersects with several related fields of study.",
        "The complexity of this topic makes it particularly interesting.",
        "Many researchers have explored different aspects of this.",
        "The historical context provides useful background here.",
    ]

    result = list(words)
    while len(result) < target_words and elaborations:
        phrase = rng.choice(elaborations)
        result.extend(phrase.split())
        elaborations.remove(phrase)

    return " ".join(result[:target_words])
